# Generated by Django 4.1.3 on 2024-04-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.IntegerField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'instagram_response',
            },
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kol_id', models.IntegerField()),
                ('rating', models.FloatField()),
                ('status', models.CharField(max_length=128)),
                ('reputation_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'reputation',
            },
        ),
        migrations.CreateModel(
            name='YoutubeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_channel_id', models.IntegerField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'youtube_channel_response',
            },
        ),
    ]
